import {
  SimAgent,
  TurnLog,
  Position,
  SimulationPhase,
  DecisionPoint,
  DecisionRecord,
} from "@/types";
import type { EffectivePlayerPlan } from "@/lib/normalizePlan";

/**
 * Cursor structure for the resumable phase loop.
 *
 * The sim runs by advancing cursors one sub-step at a time (one utility
 * placement, one agent path, one duel, one spike step). Between every
 * sub-step we consult `decisions/detectors` to decide whether to pause the
 * run and surface an emergent decision to the player.
 */
export type RunnerPhase =
  | "setup"
  | "utility"
  | "movement"
  | "combat"
  | "spike"
  | "done";

export interface CombatCursor {
  /** Attackers are resolved first (initiators lead), then defenders opportunistically. */
  side: "attacker" | "defender";
  index: number;
  sortedAttackers: string[];
  sortedDefenders: string[];
  engagedDefenders: string[];
}

/**
 * Compact, JSON-serializable representation of the simulation's live state.
 * Arrays are used in place of Set/Map so the server can persist and restore
 * the state verbatim between round-trips.
 */
export interface SimState {
  plan: EffectivePlayerPlan;
  scenarioId: string;
  /** Seed used to initialise the RNG on resume. */
  seed: number;
  /** Current RNG state (mulberry32 counter). */
  rngState: number;

  phase: RunnerPhase;

  // Cursors per phase
  utilityCursor: number;
  movementCursor: number;
  movementOrder: string[]; // agentIds in execution order (shortest path first)
  combat: CombatCursor;
  spikeDone: boolean;

  // World
  agents: SimAgent[];
  smokeTiles: string[];
  wallTiles: string[];
  mollieTiles: string[];
  /** key → ownerAgentId. Serialized as [key, ownerId] pairs. */
  trapTiles: [string, string][];

  // Accumulated log
  turns: TurnLog[];

  // Decision bookkeeping
  decisionPoints: DecisionPoint[];
  decisionHistory: DecisionRecord[];
  /** The decision we're currently waiting on the player for, if any. */
  pendingDecision?: DecisionPoint;

  // Detector memoization — prevents the same moment firing twice.
  seenFirstContact: boolean;
  seenAllyDowns: string[]; // agentIds already acknowledged
  seenReconReveals: string[]; // enemy agentIds already surfaced
  seenSpikeThresholds: number[]; // seconds marks already triggered (e.g. 30, 15)
  seenLowHpDuels: string[]; // agentIds already prompted for a low-hp duel

  /** Simulated time-remaining on the spike clock (seconds). */
  spikeSecondsLeft: number;

  /** Next sequential id for decision points generated by this run. */
  decisionIdCounter: number;

  /** Choice "effect mutations" queued by `apply()` that the next phase step should honor. */
  pendingMutations: PendingMutation[];
}

/**
 * Mutations scheduled by decision-choice `apply()` callbacks. Kept as
 * discriminated unions so they serialize cleanly across the wire and the
 * phase stepper can resolve them without re-running the whole detector.
 *
 * The majority of these produce visible `GameEvent`s on application — the
 * user should always be able to tell which mutation landed by watching the
 * cinematic.
 */
export type PendingMutation =
  | { kind: "inject_smoke"; position: Position; radius: number; agentId: string }
  | { kind: "inject_mollie"; position: Position; radius: number; agentId: string }
  | { kind: "inject_flash"; position: Position; agentId: string; angle?: number }
  | { kind: "reposition_agent"; agentId: string; position: Position }
  /** Shift a single agent a short distance toward `toward`. Emits `agent_move`. */
  | { kind: "path_veer"; agentId: string; toward: Position; distance: number }
  /** Shift multiple agents toward `toward` (e.g. "collapse on site"). */
  | {
      kind: "group_push";
      agentIds: string[];
      toward: Position;
      distance: number;
      stim?: number;
    }
  | { kind: "reveal_defender"; defenderId: string }
  | { kind: "stim_advantage"; agentId: string; amount: number }
  | { kind: "cancel_next_duel_for"; agentId: string }
  /** Mark a defender blind — their next duel is heavily advantaged vs attackers. */
  | { kind: "blind_defender"; defenderId: string }
  /** Move a given attacker to the front of the combat queue (re-prioritise). */
  | { kind: "swap_duel_order"; firstAgentId: string }
  | { kind: "force_defuse_attempt" }
  | { kind: "abort_retake" };

/** Result shape returned by every `stepSimulation` call. */
export interface StepResult {
  /** Everything generated since the previous step returned. */
  segment: TurnLog[];
  /** Set when the run paused waiting for a player decision. */
  pendingDecision?: DecisionPoint;
  /** Set when the run finalised. The caller should use `state.turns` + this for the replay. */
  finalised?: boolean;
}

export function serializeSimState(state: SimState): string {
  return JSON.stringify(state);
}

export function deserializeSimState(raw: string): SimState {
  const parsed = JSON.parse(raw) as SimState;
  // Re-seed runtime-only defaults if an older serialization is missing them.
  parsed.pendingMutations = parsed.pendingMutations ?? [];
  parsed.decisionPoints = parsed.decisionPoints ?? [];
  parsed.decisionHistory = parsed.decisionHistory ?? [];
  parsed.seenAllyDowns = parsed.seenAllyDowns ?? [];
  parsed.seenReconReveals = parsed.seenReconReveals ?? [];
  parsed.seenSpikeThresholds = parsed.seenSpikeThresholds ?? [];
  parsed.seenLowHpDuels = parsed.seenLowHpDuels ?? [];
  return parsed;
}

/** Phase-label for log TurnLog entries. */
export function phaseToLogKey(phase: RunnerPhase): SimulationPhase {
  if (phase === "setup") return "setup";
  if (phase === "utility") return "utility";
  if (phase === "movement") return "movement";
  if (phase === "combat") return "combat";
  if (phase === "spike") return "spike";
  return "setup";
}
